### PR TITLE
Set up Hound

### PR DESCRIPTION
**Pull request by kaishin**

### CODE REVIEW

**Comment by Magnus-G** [comment]
@kaishin excellent... Go for it. :radio:

**Comment by teoljungberg** [comment]
Could you also enable ruby-support @kaishin

**Comment by tysongach** [comment]
Be warned: I found that Hound for SCSS has lots of bugs at the moment…

**Comment by tysongach** [comment]
The Hound issue was resolved. Let’s enable it here and give it another try…

Do we need to include the `scss-lint.yml` again? I was under the impression that Hound has the Neat one built-in already? Can we only add it if we need slight overrides? Does Hound work that way?

**Comment by kaishin** [comment]
Good question @tysongach. I have been including it for local linting so we should keep it either way.

**Comment by tysongach** [comment]
@kaishin :+1: 

I agree with @teoljungberg’s comment above, to enable Ruby too, otherwise let’s get this merged in.

**Pull request merged**
