### PR TITLE
Remove Browser

### PR DESCRIPTION
**Pull request by Magnus-G**

### CODE REVIEW

**Comment by tysongach** [comment]
:tada: :tada: :tada:

**Comment by woodall** [comment]
I was just looking for this. Curious, why was it removed?

**Comment by tysongach** [comment]
@woodall Sorry that this PR didn’t link to the original issue, but it can be found here: https://github.com/thoughtbot/refills/issues/211

**Comment by woodall** [comment]
Ahh yes. Thanks for the guidance.  :walking:

**Pull request closed without merging**
