### PR TITLE
Update viewport meta tag

### PR DESCRIPTION
**Pull request by tysongach**
Remove `user-scalable=no` so that people can zoom the page.

### CODE REVIEW

**Comment by creuter** [comment]
Good catch, I'm surprised this was the default

**Comment by tysongach** [comment]
> …I'm surprised this was the default

Was this from a Middleman create command or something? Maybe we could intro a change further up the chain…

**Comment by tysongach** [comment]
Ah, seems like it [came from here](https://github.com/middleman/middleman-templates-default/blob/master/template/source/layouts/layout.erb#L6)?

**Comment by creuter** [comment]
@tysongach Looks like it, I just tracked that down as well. I'll follow up with a PR there.

**Comment by tysongach** [comment]
> I'll follow up with a PR there.

@creuter Already on it 😉

**Pull request merged**
