### PR TITLE
Refills haml

### PR DESCRIPTION
**Pull request by JsusMillan**
branch modifications to work with haml. generates html.haml

### CODE REVIEW

**Comment by tysongach** [comment]
@JsusMillan Hi, thanks for the PR! Would you mind providing some background context for moving to Haml?

**Comment by Magnus-G** [comment]
@JsusMillan, @tysongach I see the reason why some people might prefer Haml.
@teoljungberg could this be generated, kind of like we generate the Coffeescript? And be presented like so:

image

**Comment by teoljungberg** [comment]
After a quick googling around - we can generate HAML from the HTML we have. And I think that's a better route to go down than completely go over to HAML.

@JsusMillan Could you modify your PR to follow that instead? You can look how to coffee generation is being made and follow suit on that.

/cc @Magnus-G

**Comment by tysongach** [comment]
@JsusMillan Any update here, per @teoljungberg’s comment above?

**Comment by tysongach** [comment]
Closing due to lack of response.

**Pull request closed without merging**
