### PR TITLE
Unbreak builds

### PR DESCRIPTION
**Pull request by teoljungberg**
- Fetch `generator_spec` from github
When installing `generator_spec` via rubygems, it downloads another
version of the gem instead of the latest and greatest. For some oddball
reason
- Add ruby 2.1 to run on travis
- Drop jruby from travis

### CODE REVIEW

**Comment by teoljungberg** [comment]
I'm dropping jruby from travis because jruby tries to install `thin`(which is not apart of our `Gemfile`). Probably due to the fact that jruby does not support C-extensions, it prefers having gems use it's corresponding JVM-bindings. One of the gems then swaps out `A_GEM`(I still haven't found where the culprit is) and replaces it with `thin`.

Let's just drop it!

**Comment by tysongach** [comment]
This should get a review from a thoughtbot developer before merging!

**Comment by teoljungberg** [comment]
@tysongach I have talked it with @gabebw about the issue, but yeah. And I should have clarified that, or even asked him to sign off before.

**Comment by gabebw** [comment]
This looks reasonable, though i'd sort the rubies in travis.yml by number. "2.0.0, 1.9.3, 2.1" looks odd

**Comment by teoljungberg** [comment]
@gabebw right, fixed in 32dff5d

**Pull request merged**
