### PR TITLE
Remove intro text refill

### PR DESCRIPTION
**Pull request by tysongach**
I don’t think it adds much value; it seems pretty basic.

### CODE REVIEW

**Comment by Magnus-G** [comment]
I don't agree. I use – and see – this pattern a lot and it's convenient to just copy paste it. As long as the copy-pasting is quicker than creating something from scratch I think it deserves a place in Refills.

**Comment by tysongach** [comment]
I guess the bigger question is: what is this pattern? What does it do? Is it just a slightly larger font size for the opening paragraph?

If so, when I needed a pattern like that, this is how I would do it:

```html
<article>
  <p class="article-intro">Lorem ipsum dolor sit amet, consectetur consectetur adipisicing elit. Perferendis para mitis eun non ullam atque debitis, illo adipisicing elit. Perferendis para mitis eun non ullam atque debitis, illo. Amet, consectetur adipisicing.</p>
  <!-- article content -->
</article>
```

```scss
.article-intro {
  font-size: modular-scale(1);
}
```

I would say that I don’t need to copy-paste that.

_If_ the component is a larger font-size on the opening paragraph _and_ a little badge at the top (where it says “TOPIC LABEL”), then I would say this component needs to re-use the existing [Refills Badge](http://refills.bourbon.io/components/#badges). Reduce code repeating and minimize maintenance. Build larger modules with multiple existing components.

**Comment by tysongach** [comment]
@teoljungberg Do you know why the build keeps breaking?

**Comment by teoljungberg** [comment]
@tysongach the build are failing because the files you removed are still being looked for in the tests https://github.com/thoughtbot/refills/blob/212b747fe85149adc85b569375cbd7fa69f25cb5/spec/refills/import_generator_spec.rb#L24

**Comment by tysongach** [comment]
@Magnus-G Any comment on my note above? I still don’t see the big value in this pattern?

**Comment by Magnus-G** [comment]
@tysongach let's remove it!

**Pull request merged**
