### PR TITLE
Remove prefixes

### PR DESCRIPTION
**Pull request by tysongach**
This PR is setting the stage for an eventual move to Bourbon 5, which no longer has prefixing mixins.

This PR does _not_ make Refills fully compatible with Bourbon 5, but it does get rid of old Bourbon mixins which purpose can easily be taken over by Autoprefixer. So not dependency/requirements really change here, really (just, bring your own prefixing: BYOP).

### CODE REVIEW

**Comment by Magnus-G** [comment]
@tysongach this is great! Apart from the comma-nitpicks it looks good to merge as soon as you are ready to ship Bourbon 5.

**Comment by tysongach** [comment]
Thanks, @Magnus-G! I wanted to maintain an 80-character line length, but I don’t think we have a guide around how we do that along with those comma warnings from SCSS-Lint/Hound…

Regarding Bourbon 5: This PR does not introduce a dependency on it and I think we should merge without waiting for 5. I purposely didn’t want to introduce a forced upgrade to 5 yet, but these changes are working towards that.

Ultimately, Sass is the wrong tool for prefixing and we (at thoughtbot) use Autoprefixer by default, others can use the prefixing tool of their choice. Refills just won’t provide prefixed CSS out of the box, anymore.

**Comment by tysongach** [comment]
Ah, I think Hound is speaking directly about the `rgba()` function argument commas…fixing that now.

**Comment by Magnus-G** [comment]
Merging this now! Thanks @tysongach for great work!

**Comment by Magnus-G** [comment]
I'll go in and fix some broken images and such on this branch tomorrow. Then we can merge it!

**Comment by tysongach** [comment]
@Magnus-G Oh, shoot! Did I break some images? I went through (and just did again) and didn’t notice any visual regressions. Specifically images are broken?

**Comment by Magnus-G** [comment]
@tysongach very strange... Might have been a caching issue or something on my end. All looks well again and I have merged it now!

**Pull request closed without merging**
